<?php


define('VERSION', "2.3.0.9");
define('CHILD_NT_AMAZE_INC', get_stylesheet_directory_uri());
define('CHILD_NTAMAZE_CSS', get_stylesheet_directory_uri());
define('CHILD_NTAMAZE_JS',  get_stylesheet_directory_uri());


/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
        * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
        * you will have to make sure to maintain all of the parent theme dependencies.
        *
        * Make sure you're using the correct handle for loading the parent theme's styles.
        * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
        * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
        *
        * @link https://codex.wordpress.org/Child_Themes
        */




function ntamaze_child_enqueue_styles()
{
    wp_enqueue_style(
        'nt-amaze-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        false,
        VERSION
    );
    wp_enqueue_style(
        'nt-amaze-child-style-2',
        get_stylesheet_directory_uri() . '/css/light-style.css',
        false,
        VERSION
    );
}

add_action('wp_enqueue_scripts', 'ntamaze_child_enqueue_styles');


add_action('widgets_init', 'my_register_sidebars');
function my_register_sidebars()
{
    /* Register the 'primary' sidebar. */
    register_sidebar(
        array(
            'name' => esc_html__('Blog Sidebar English', 'nt-amaze'),
            'id' => 'sidebar-english',
            'description' => esc_html__('These are widgets for the Blog page.', 'nt-amaze'),
            'before_widget' => '<div class="sidebar-widget %2$s">',
            'after_widget' => '</div>',
            'before_title' => '<h4 class="widget-title">',
            'after_title' => '<div class="border-width"></div><div class="space-10"></div></h4>'
        )
    );
    /* Repeat register_sidebar() code for additional sidebars. */
}


function pointcom_carregando_scripts()
{

    wp_enqueue_script('pointcom_maskJS', get_stylesheet_directory_uri() . '/js/masks_jquery.js', array('jquery'), VERSION, true);
    wp_enqueue_script('pointcom_mask', get_stylesheet_directory_uri() . '/js/mask.js', array('jquery'), VERSION, true);

    // Template-custom js
    wp_deregister_script('template-custom');
    wp_enqueue_script('template-custom', CHILD_NTAMAZE_JS . '/js/template-custom.js', array('jquery'), VERSION, true);
}
add_action('wp_enqueue_scripts', 'pointcom_carregando_scripts');

function ti_custom_javascript()
{
    if (is_home() || is_front_page() || is_page("en")) {
?>
        <style>
            .contact-details:before {
                content: '';
                background-repeat: no-repeat;
                background-image: url('<?php echo CHILD_NTAMAZE_CSS; ?>/imgs/loja1.jpg');
                min-height: 362px;
                width: 221px;
                position: relative;
                float: left;
                background-size: contain;
                margin-right: 32px;
            }

            .btn-coruja {
                background-image: url('<?php echo CHILD_NTAMAZE_CSS; ?>/imgs/coruja-azul.png') !important;
            }



            @media (max-width: 768px) {
                .contact-details:before {
                    width: 100%;
                    margin: 20px auto;
                    display: block;
                    float: none;
                    background-position: center;
                }

            }
        </style>
    <?php
    }
}
add_action('wp_footer', 'ti_custom_javascript');

function get_url_page_translate($path = "/")
{
    $url = home_url($path);


    if (!is_home() && !is_front_page() && !is_page("en")) {
        $url .= get_post_field('post_name', get_post());
    }

    return $url;
}

function replace_url_menu($url)
{

    if (strpos($url, get_home_url()) === false) {
        $url = str_replace('/novo', get_home_url(), $url);
    }

    return $url;
}


function mmn_main_item_rewrite($items, $args)
{
    foreach ($items as $key => $item) {

        $item->url = replace_url_menu($item->url);
    }

    return $items;
}
add_filter('wp_nav_menu_objects', 'mmn_main_item_rewrite', 1, 2);


add_action('my_form_search', 'my_form_search', 10, 2);
function my_form_search($language = "pt-BR")
{

    ?>
    <form role="search" method="get" class="search-form" action="<?php echo home_url('/'); ?>">
        <div class="wp-block-search__inside-wrapper " style="width: 666px">
            <input type="hidden" name="lang" value="<?php echo $language; ?>">
            <input type="search" class="wp-block-search__input " placeholder="<?php echo esc_attr_x('', 'placeholder') ?>" value="<?php echo get_search_query() ?>" name="s" title="<?php echo esc_attr_x('Search for:', 'label') ?>" />
            <input type="submit" class="wp-block-search__button  " value="<?php echo $language == "en" ? "Search" : "Pesquisar"; ?>" />
        </div>
    </form>
<?php

}


add_action('my_posts_recents', 'my_posts_recents', 10, 2);
function my_posts_recents($language = "pt-BR")
{

?>
    <div id="my_posts_recents">
        <h4 class="widget-title"> <?php echo $language == "en" ? "Posts Recents" : "Posts Recentes"; ?>
            <div class="border-width"></div>
            <div class="space-10"></div>
        </h4>

        <div class="sidebar-widget">
            <ul class="wp-block-categories-list wp-block-categories">
                <?php

                $category_id = get_cat_ID('english');


                $array_query = array(
                    'numberposts' => 4, // Number of recent posts thumbnails to display
                    'post_status' => 'publish', // Show only the published posts,
                );

                if ($language == 'en') {
                    $array_query["category_name"] = "english";
                } else {
                    $array_query["category__not_in"] = $category_id;
                }


                $recent_posts = wp_get_recent_posts($array_query);
                foreach ($recent_posts as $recent) {
                    printf(
                        '<li class="cat-item cat-item-30 current-cat"><a href="%1$s">%2$s</a></li>',
                        esc_url(get_permalink($recent['ID'])),
                        apply_filters('the_title', $recent['post_title'], $recent['ID'])
                    );
                }
                ?>
            </ul>
        </div>
    </div>

<?php

}



add_action('my_categories', 'my_categories', 10, 2);

function my_categories($language = "pt-BR")
{

?>
    <div id="my_posts_recents">
        <h4 class="widget-title"> <?php echo $language == "en" ? "Categories" : "Categorias"; ?>
            <div class="border-width"></div>
            <div class="space-10"></div>
        </h4>

        <div class="sidebar-widget">
            <ul class="wp-block-latest-posts__list wp-block-latest-posts">

                <?php
                $categories = get_categories(array(
                    'orderby' => 'name',
                    'parent'  => 0
                ));

                foreach ($categories as $category) {
                    printf(
                        '<li><a href="%1$s" class="wp-block-latest-posts__post-title">%2$s</a></li>',
                        esc_url(get_category_link($category->term_id)),
                        esc_html($category->name)
                    );
                }
                ?>

            </ul>
        </div>
    </div>

<?php

}

add_action('my_custom_html_right', 'my_custom_html_right', 10, 2);

function my_custom_html_right($language = "pt-BR")
{
?>

    <div class="col-md-3">
        <div id="widget-area" class="  margin-b-40">

            <div class="box-right">
                <?php do_action('my_form_search', $language); ?>
                <br>
                <?php do_action('my_posts_recents', $language); ?>
                <?php do_action('my_categories', $language); ?>
            </div>
            <?php if (is_active_sidebar('sidebar-english')) : ?>
                <?php //dynamic_sidebar('sidebar-english'); 
                ?>
            <?php endif; ?>
        </div><!-- .widget-area -->
    </div>
<?php
}
